### ISSUE TITLE
Dynamic QR-Code in Atlas Issue

### ISSUE THREAD

**Issue by WalterWHeisenberg** [gkahiu/qrbarcodeitem-plugin#1]
I have inserted a QR code into an atlas. 
Via this expression the QR code should be changed depending on the feature respective the value from the field 'URL'.  Unfortunately, this does not happen.
If I use the same expression in a text field, the text changes when I switch between the pages of the atlas.
I use the following expression:

[%attribute(@atlas_feature,'URL')%]

I am running QGIS 3.16.1

Thanks for the effort

**Comment by gkahiu** [comment]
Hi,

Thanks for the feedback. Just to understand - does the QR code show (but is not changing) or it does not show at all?

**Comment by WalterWHeisenberg** [comment]
The QR-Code is showing on the layout. In my example the first URL is showing correct by the code. When i now start switching the altas pages nothing happens. Nothing meens, that the Code is not changing, it shows the URL from the first  feature. 
However, when I use for example the spacebar in the Expression Builder, the code changes. 

Thx

**Comment by gkahiu** [comment]
Thanks, will look into it and push a fix.

**Comment by gkahiu** [comment]
Hi Walter,

I have pushed a fixed in v0.1.1, kindly update the plugin and let me know if the issue has been resolved.

**Comment by WalterWHeisenberg** [comment]
Hi Kahiu,
many thanks for the work and the bug fixing. For me it works now!
