### ISSUE TITLE
Generating QR code with http link and extra parameters

### ISSUE THREAD

**Issue by ClaudeVer** [gkahiu/qrbarcodeitem-plugin#10]
I need through a QR code give an https adress, with parameters, like 'https://MyWebSite/Mywebpage?Myparam=1234'
The objective is to open a specific page of MyWebsite, and pass the parameter MyParam for further use in the page (ie prefill specific fields depending of the value passed.
I do not find the correct way of setting up this string, knowing that :
"https://MyWebSite/Mywebpage" is a constant, as well as "?Myparam=" and 1234 is the content of an attribute field.
The problems start with the ? that does  not seem to be accepted/recognised.
I tested with the concat function, or with double pipes, but without success, the concat does not seem to be executed and is part of the QR code generated.
Any idea to have it work?
I also posted this question on stackexchange

Claude

**Comment by gkahiu** [comment]
The question mark symbol is accepted, see the corresponding text for the sample expression shown below:

![image](https://user-images.githubusercontent.com/3840267/226272177-f361940e-249f-4edc-b19d-dfbb16d78682.png)

I have separated the '1234' just to illustrate that this can be fetched from an attribute table.

You can read more about writing expressions [here](https://docs.qgis.org/3.28/en/docs/user_manual/expressions/expression.html).

**Comment by ClaudeVer** [comment]
Thank you. I rework with your example and It Works fine. 👍Claude VerstichelLe 20 mars 2023 à 08:24, Kahiu ***@***.***> a écrit :﻿
The question mark symbol is accepted, see the corresponding text for the sample expression shown below:

I have separated the '1234' just to illustrate that this can be fetched from an attribute table.
You can read more about writing expressions here.
